metadata:
  name: grafana
spec:
  tokenPolicies:
    - default
    - grafana-read
  tokenTtlSeconds: 3600 # 1 hour
  serviceAccountNames:
    - external-secrets
  serviceAccountNamespaces:
    - external-secrets
