metadata:
  name: terraform_grafana
spec:
  # role type; can be "static" or "dynamic"
  type: static
  # name of the database user to associate to the role; omit to generate dynamic roles with unique usernames
  # NOTE: the user MUST EXIST in the database
  username: terraform_grafana
  # the number of seconds between password rotations
  # WARN: CANNOT be used with rotationSchedule or rotationWindow
  rotationPeriodSeconds: 2592000 # 30 days
